apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: node-hello-world-docker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'node-hello-world:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/deepakchampatiray/node-hello-docker.git'
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    -
      type: ImageChange
    - generic:
        secret: 8fd5b51323e0a62f
      type: Generic
    - github:
        secret: 180f7ca1edc5cd06
      type: GitHub
status:
  lastVersion: 1
